edition = "2024"
max_width = 80
chain_width = 50
use_small_heuristics = "Max"
comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Mixed"
wrap_comments = true
fn_args_layout = "Compressed"